pom.xml

- Use java version 1.6 and not 1.4
- Group Id was removed, as no more inherited by parent, thus blocking release process

Mime4J 252 

---

assemble/pom.xml
james-utils/pom.xml
pom.xml

```
1 [INFO]   com.google.guava:guava .............................. 18.0 -> 28.1-jre
9 [INFO]   commons-io:commons-io ..................................... 2.4 -> 2.6
9 [INFO]   commons-logging:commons-logging ......................... 1.1.1 -> 1.2
9 [INFO]   junit:junit ...................................... 4.10 -> 4.12
9 [INFO]   log4j:log4j ......................................... 1.2.14 -> 1.2.17
18 [INFO]   org.apache.maven.doxia:doxia-core ......................... 1.2 -> 1.9
9 [INFO]   org.assertj:assertj-core ............................. 1.7.1 -> 3.13.2
9 [INFO]   org.mockito:mockito-core .............................. 1.9.5 -> 3.0.0
1 [INFO]   org.slf4j:slf4j-api ............................ 1.7.7 -> 1.7.18
```

MIME4J-289 Upgrade libs

---

core/src/main/java/org/apache/james/mime4j/codec/DecoderUtil.java
core/src/test/java/org/apache/james/mime4j/codec/DecoderUtilTest.java

It it very common to recieve mislabeled charsets for windows-1252, which usually end up
being ISO-8898-1. This is a minimal change allows our email servers to not have to rewrite
q-encoding, but doesn't change any default behaviors within Mime4J.
/cc @ryanpbrewster

MIME4J-295 Allow for overriding the specified charset when decoding q or b encoded words

---

dom/src/test/java/org/apache/james/mime4j/dom/MessageCharsetLenientTest.java
james-utils/src/test/java/org/apache/james/mime4j/utils/search/MessageMatcherTest.java
pom.xml

Changes:
* There was a maven plugin that needed to be updated
* `iso-8859-16` is a legal charset that the JDK now supplies
* `com.sun.org.apache.bcel.internal.util.ClassLoader` was not found during compiling, so I switched to the builtin ClassLoader
Result:
The tests pass for me on a macbook with JDK 15 and mvn `3.6.3`

MIME4J-290 Fix build for recent mvn and JDK versions

---

pom.xml

While running tests for https://github.com/apache/james-mime4j/pull/35 https://github.com/apache/james-mime4j/pull/34 the ANT plugin was failing...

JAMES-3226 Ignore Antora doc missing licenses

---

core/src/main/java/org/apache/james/mime4j/parser/MimeStreamParser.java

All other options can be set, except that one. And of course this is the one I'm interested in.
I guess this can't make it into an earlier version than 0.8?
https://issues.apache.org/jira/browse/MIME4J-255

Add method to allow setting of "no recurse" mode to underlying mime token stream

---

dom/src/main/java/org/apache/james/mime4j/dom/Header.java
dom/src/main/java/org/apache/james/mime4j/message/AbstractHeader.java

Preserving the "grouped by name" structure can ease the work of callers.

MIME4J-299 Access to the Header map

---

core/src/main/java/org/apache/james/mime4j/stream/FallbackBodyDescriptorBuilder.java
core/src/main/java/org/apache/james/mime4j/stream/Field.java
core/src/main/java/org/apache/james/mime4j/stream/RawField.java
dom/src/main/java/org/apache/james/mime4j/dom/Message.java
dom/src/main/java/org/apache/james/mime4j/dom/field/FieldName.java
dom/src/main/java/org/apache/james/mime4j/field/AbstractField.java
dom/src/main/java/org/apache/james/mime4j/field/DelegatingFieldParser.java
dom/src/main/java/org/apache/james/mime4j/internal/AbstractEntityBuilder.java
dom/src/main/java/org/apache/james/mime4j/message/AbstractEntity.java
dom/src/main/java/org/apache/james/mime4j/message/AbstractHeader.java
dom/src/main/java/org/apache/james/mime4j/message/AbstractMessage.java
dom/src/main/java/org/apache/james/mime4j/message/DefaultBodyDescriptorBuilder.java
dom/src/main/java/org/apache/james/mime4j/message/DefaultMessageWriter.java

18% of CPU time of Message.Builder.parse is held by toLowerCase calls.
6,75% of CPU is used by toLowerCase calls...

MIME4J-302 MessageBuilder::parse repeatedly calls toLowerCase on header names

---

dom/src/main/java/org/apache/james/mime4j/field/DateTimeFieldLenientImpl.java
dom/src/test/java/org/apache/james/mime4j/field/LenientDateTimeFieldTest.java

This allows:
- Specifying all patterns at once, avoiding one parsing pass per pattern
- DateTimeFormatter is thread safe, thus can be initialized once and reused
`AbstractMessage.getDate` represents 6.5% of total memory allocation and 2.5% of CPU allocations in my James JMAP performance tests, doing many parser initialization and parsing passes.
Below is a flame graph detailing operations performed.
This work is inspired from @aduprat work on `ImapDateTimeFormatter` in James code base.

MIME4J-298 Convert DateTimeFieldLenientImpl to DateTimeFormatter

---

dom/src/main/java/org/apache/james/mime4j/field/DateTimeFieldLenientImpl.java

Removing it breaks no tests, as 0000 is the
default GMT.
This prevents one defensive copy of the
parsed entity thus gets parsing slightly
faster.

MIME-298 DateTimeFieldLenientImpl: remove unneeded option

---

core/src/main/java/org/apache/james/mime4j/util/ContentUtil.java

StringBuilder is an expensive construct, we spend most of our time, for each character, ensuring the capacity of the string builder.
Size being known, the operation simple, we can directly operate on top of a char array.
Gains: 78%
(combine with MIME4J-304 and unfold operations)

MIME4J-305 ContentUtil::decode can avoid using StringBuilder

---

core/src/main/java/org/apache/james/mime4j/util/MimeUtil.java

Calling repeatedly append requires ensuring the capacity amongst other.
Appends to the string builder can be done for all previous chars when a line delimiter is encountered, thus reducing the cost of the operation.
Gain: 66%

MIME4J-306 MimeUtil::unfold should group char appends

---

pom.xml

Or is there something more that needs to be done in order to push `-javadoc.jar`s to Maven Central?
They're not there now: https://repo1.maven.org/maven2/org/apache/james/apache-mime4j-core/0.8.5/

Add maven-javadoc-plugin

---

core/src/main/java/org/apache/james/mime4j/util/MimeUtil.java

SimpleDateFormat usage is sub - optimal, we should favor `DateTimeFormatter` and leverage its efficiency + thread safety

MIME4J-309 MimeUtil::date0 should use DateTimeFormatter

---

core/src/main/java/org/apache/james/mime4j/util/MimeParameterMapping.java
dom/src/main/java/org/apache/james/mime4j/field/ContentDispositionFieldImpl.java
dom/src/main/java/org/apache/james/mime4j/field/ContentDispositionFieldLenientImpl.java
dom/src/main/java/org/apache/james/mime4j/internal/ParameterHelper.java
dom/src/main/javacc/org/apache/james/mime4j/field/contentdisposition/ContentDispositionParser.jj
dom/src/test/java/org/apache/james/mime4j/field/ContentDispositionFieldTest.java
dom/src/test/java/org/apache/james/mime4j/field/LenientContentDispositionFieldTest.java

Hello, I'm proposing fixes for MIME4J-109. As suggested [pull64](https://github.com/apache/james-mime4j/pull/64) is closed and this one is created based on the code review. please let me know if any clarification is needed. Thanks

fix: use correct character encoding when parsing of MIME parameter value

---

dom/pom.xml

The javacc-maven-plugin recently got a major upgrade to 3.0.0. The modifications are generating numerous errors in our code that depends on 2.6.
This fixes the build on master that is failing for the above reason

Add version for the javacc-maven-plugin

---

dom/src/main/javacc/org/apache/james/mime4j/field/datetime/DateTimeParser.jj
dom/src/test/java/org/apache/james/mime4j/field/DateTimeTest.java

This changes `DateTimeParser.jj` to ignore case when parsing "day-of-week" and "month".
https://issues.apache.org/jira/browse/MIME4J-320

MIME4J-320 Make DateTimeParser case-insensitive for day of week and month

---

dom/src/main/java/org/apache/james/mime4j/field/ContentTypeFieldImpl.java
dom/src/main/java/org/apache/james/mime4j/field/ContentTypeFieldLenientImpl.java
dom/src/test/java/org/apache/james/mime4j/field/ContentTypeFieldMimeParameterTest.java

I saw that support for decoding [RFC2231](https://www.rfc-editor.org/rfc/rfc2231)-style encoded MIME parameters was added in #66. Unfortunately, the implementation is wrong in some cases and is not handling quite a few (admittedly exotic) edge cases.
This PR adds the tests we're using in K-9 Mail. You can find our implementation here: [`MimeParameterDecoder`](https://github.com/thundernest/k-9/blob/9cf73c99d09332a461ecb3830db86bca044bdf2e/mail/common/src/main/java/com/fsck/k9/mail/internet/MimeParameterDecoder.kt)
The currently failing tests are disabled using the `@Ignore` annotation. `ContentTypeParser` is currently missing support for RFC 2231 entirely. But copying the mechanism used in `ContentDispositionParser` won't make all of these tests pass. Additional work is required.
/cc: …

MIME4J-109 Add tests for MIME parameter decoding

---

dom/src/main/java/org/apache/james/mime4j/dom/SingleBody.java
dom/src/main/java/org/apache/james/mime4j/message/BasicBodyFactory.java

A quite common need is for instance to get the size off attachments.
Today the DOM API offer no other ways than to read the inputstream of the Body Part and manually compute the size.
However, implementation holding the raw data might already have this value pre-computed and this could be used to get the size very cheaply, without copies.
I propose to add a default "copy" implementation, and provide more optimal implementations where possible.

MIME4J-321 SingleBody should return its size

---

core/src/main/java/org/apache/james/mime4j/util/MimeParameterMapping.java
dom/src/test/java/org/apache/james/mime4j/field/LenientContentDispositionFieldTest.java

Multipart UTF-8 attachment filenames weren't properly decoded. Please, see a sample in the extended test.

Multipart utf-8 filename

---

dom/src/test/java/org/apache/james/mime4j/field/address/LenientAddressBuilderTest.java

Huge thanks to Chung dae hyun for reporting the issue and writing the test Huge thanks to @twn for fixing utf-8 handling in the first place and fixing up the test

MIME4J-327 LenientAddressParser now handles UTF-8

---

core/src/main/java/org/apache/james/mime4j/io/MimeBoundaryInputStream.java
core/src/test/java/org/apache/james/mime4j/parser/ExtractPartWithDifferentLengthsTest.java

Root cause:
In ExtractPartWithDifferentLengthsTest:
```
for (int i = 1; i <= 5000; i++) {
partBuilder.append(i % 80 == 0 ? "\n" : "A");
```
when the content part input reaches a specific length, due to the limit of the buffer in MimeBoundaryInputStream, the parser extract the content part with '\r' at the end (without '\n').
```
+ "--QvEgqhjEnYxz\n"
+ "Content-Type: text/plain\n"
+ "\n"
+ part
+ "\r\n"
+ "--QvEgqhjEnYxz--\n";
```
It seems in mime4j, '\r' without '\n' is still considered as a new line. Therefore, a new empty line is added at the end of content part.

MIME4J-330 Fix MimeStreamParser bug: part body stream ends with CR

---

core/src/main/java/org/apache/james/mime4j/stream/RawFieldParser.java
core/src/test/java/org/apache/james/mime4j/parser/MimeStreamParserTest.java
core/src/test/java/org/apache/james/mime4j/parser/TestHandler.java
core/src/test/java/org/apache/james/mime4j/stream/RawFieldParserTest.java
core/src/test/java/org/apache/james/mime4j/stream/RawFieldTest.java
dom/src/main/java/org/apache/james/mime4j/field/address/LenientAddressParser.java
dom/src/main/jjtree/org/apache/james/mime4j/field/address/AddressListParser.jjt
dom/src/test/java/org/apache/james/mime4j/field/address/DefaultAddressBuilderTest.java
dom/src/test/java/org/apache/james/mime4j/field/address/LenientAddressBuilderTest.java

Not much to do here — code written in Java can hardly avoid having good support for unicode strings.
- The syntax for an atom has been extended. 
- Two places silently assumed that he length of a string in bytes is the same as its length in characters.
- Tests.
James now assumes that if "8-bit" header field values aren't otherwise labelled, then they are UTF8. That was _mostly_ the case before, now it's _always_ the case AFAICT.

Add support for RFC 6532, and test it.

---

core/src/main/java/org/apache/james/mime4j/stream/Field.java
core/src/main/java/org/apache/james/mime4j/stream/RawField.java
core/src/test/java/org/apache/james/mime4j/stream/RawFieldTest.java
dom/src/main/java/org/apache/james/mime4j/field/AbstractField.java
dom/src/main/java/org/apache/james/mime4j/message/DefaultMessageWriter.java

That would allow projects using the mime4j library to be able to get a raw field without it returning a null value, to protect against potential NPE, without introducing breaking changes with its core API.
The computing of the raw value in case it's null is based on what was in writeField method in DefaultMessageWriter.

MIME4J-333 Introducing a getSafeRaw() method in RawField
